name: Docker Build and Push
description:
inputs:
  image_name:
    description: The Docker image name  (e.g., my-image).
    required: true
  tag_version:
    description: The Docker image tag (e.g., latest, 18032024-SNAPSHOT)
    required: true
  registry:
    description: The Docker registry URL (e.g., internal-docker-repo).
    required: true

runs:
  using: "composite"
  steps:
    # Login to docker registry
    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_TOKEN }}
    # Validate Login
    - name: Verify Docker Login
      run: docker info
      shell: bash
    # Build image and push to registry
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.tag_version }}
